### ISSUE TITLE
Geocoding address to coordinates broken

### ISSUE THREAD

**Issue by timoh** [timoh/craftbeer#10]
This commit (in a branch) starts to add the functionality of geocoding addresses so as to not need coordinates from HTML5 location, but doesn't yet work: https://github.com/timoh/craftbeer/commit/9381649147ec580e1378a454c492e99a4720bc25

**Comment by techstalgist** [comment]
The functionality works now in master branch. I decided to commit directly to master because merging would probably be quite difficult.
