### ISSUE TITLE
Rails API returns the same availability data after location is changed

### ISSUE THREAD

**Issue by techstalgist** [timoh/craftbeer#12]
1. Use Isokaari, Helsinki as your address and click Show drinks ...
2. Click Your Location (top right nav)
3. Change your address to Töölönkatu, Helsinki and click Show drinks ...
4. The availability data you see in the table show distances relative to Isokaari, Helsinki instead of Töölönkatu, Helsinki.

HomeController:
caches_action :index, :all_with_distance

--> after clearing cache, the API gives correct results. Perhaps it returns the results from the cache even though the location is different?

**Comment by timoh** [comment]
Did this fix the problem: https://github.com/timoh/craftbeer/commit/1e7b59d9cc98882acee866ab8cc3e3507ba74e27 ?

**Comment by techstalgist** [comment]
That commit fixed the problem in the Rails API, but I found a new bug in the React & Redux implementation. It didn't call the API after the address had changed. Thanks to this fix https://github.com/timoh/craftbeer/commit/c507f9aa614baf84577ab4984f371c79822f5ca6 , now it calls the API when the location has changed. So now finally it should work properly.
