### ISSUE TITLE
Suggested UI change for intro screen

### ISSUE THREAD

**Issue by timoh** [timoh/craftbeer#15]
Instead of having the button for changing your address first, how about we have a "hero unit" (e.g. http://getbootstrap.com/2.3.2/components.html#typography) with a primary call to action to go ahead, and only secondarily a smaller button for changing the address.

This way it is visually clear what the intended next step is (so as to not get stuck in a loop of just changing the address).

Thoughts?

**Comment by techstalgist** [comment]
Seems like a good idea. I can implement this once the more important issues have been solved.

**Comment by techstalgist** [comment]
Jumbotron implemented in https://github.com/timoh/craftbeer/commit/61822a3dd7167567ad05d8f7ad0ecf6d307e9d49

Might need some improvements, but closing this one for now.
