### ISSUE TITLE
Feature idea: Help user with no initial results in show all drinks

### ISSUE THREAD

**Issue by timoh** [timoh/craftbeer#16]
In the show drinks view, if there are no drinks shown in the table due to too tight distance filter, we could try to help the user by either 

a) showing a text of "try increasing the distance to get more results" in a logical place, which disappears when results occur 

or 

b) automatically widen the distance filter until we have at least some results.

Thoughts?

**Comment by techstalgist** [comment]
Infotext added in https://github.com/timoh/craftbeer/commit/61822a3dd7167567ad05d8f7ad0ecf6d307e9d49

Might need to show different text if nonstocked items are also shown.
