### ISSUE TITLE
Tap events should be recognized immediately, without any lag

### ISSUE THREAD

**Issue by techstalgist** [timoh/craftbeer#27]
All code that uses onClick needs to be refactored so that the code recognizes tap events immediately, without 300ms lag.

**Comment by techstalgist** [comment]
This might fix the issue on Chrome at least. https://github.com/timoh/craftbeer/commit/109b6def07a070a4471e0ef793e784247f080076

reference: https://www.sitepoint.com/5-ways-prevent-300ms-click-delay-mobile-devices/

**Comment by timoh** [comment]
Did you try touchstart & touchend events?

* https://patrickhlauke.github.io/getting-touchy-presentation/#47

Also:

* https://github.com/ftlabs/fastclick
* https://webkit.org/blog/5610/more-responsive-tapping-on-ios/

**Comment by techstalgist** [comment]
I would have to add onTouchStart -event to all buttons / links. Maybe I'll do that, even though it sounds a bit tedious.

**Comment by timoh** [comment]
These npm modules might ease that chore:

* https://www.npmjs.com/package/react-tap-event-plugin
* https://www.npmjs.com/package/react-tappable

**Comment by techstalgist** [comment]
Should be OK now.
https://github.com/timoh/craftbeer/commit/5e6363673af4db4e7dddfe0fbc870a9fa271b251
