### ISSUE TITLE
Take use of API pagination on frontend side

### ISSUE THREAD

**Issue by timoh** [timoh/craftbeer#28]
Could use e.g.:

* https://www.npmjs.com/package/react-infinite-scroll
or 
* https://www.npmjs.com/package/react-infinite

Now that /home/distanced/ API supports pagination with GET parameter "page", (e.g. lat=xx&lng=yy&page=2}, we should make use of that. One convention is to do infinite scrolling, where scrolling down the list triggers another AJAX request that appends new items to the end of the data table.

**Comment by techstalgist** [comment]
Infinite scrolling might be good, because then no changes would be needed to sorting functionality.

**Comment by techstalgist** [comment]
But the idea of infinite scrolling sounds good.

**Comment by techstalgist** [comment]
I'm quite sure that sorting functionality has to moved from client to server side.

**Comment by techstalgist** [comment]
Just to be clear:

Assume that there are 25 drinks visible, and I have not yet changed sorting order.
Then I sort by price on ascending order --> it should show the cheapest drink among all drinks first, not the cheapest among the 25 previously visible drinks. Otherwise the user will not know that there are cheaper drinks available.

**Comment by timoh** [comment]
We'll need to supply the sort_by and sort_order parameters to the API, and then call the model in Rails like so:

`.order_by([sort_column, sort_direction])`

So I'll make a default sort (say, alphabetic ascending) and then have the API accept a sort_column and sort_direction.

All the while, the frontend might be wise to have some kind of caching so that it doesn't ditch the data it already has, but keeps it and appends the new results. i.e. when it makes a new request, it appends the results instead of replacing the old ones.

**Comment by techstalgist** [comment]
Hmm.. so if there now are 25 drinks visible and I sort by price, then the API returns a sorted set of 25 drinks (or whatever the limit is), and the frontend should keep the drinks that it had already and add only missing drinks to Redux store?

I guess that would make sense, because if I first remove all drinks from Redux store and then add only those drinks that the API returned, then some drinks would have to be fetched again when the user scrolls down the page.

I just have to ensure that the sort order is correct -- I cannot simply add the 25 drinks that API returned to the end of drinks array, because then the order would be incorrect.

**Comment by timoh** [comment]
Yes, this approach would require dual sorting: both in the backend and frontend.

**Comment by techstalgist** [comment]
I'll start working on this tomorrow. First I'll just start to use the page -parameter and react-infinite. Sorting changes can be done after that once the API supports them.

**Comment by timoh** [comment]
Due to these commits

https://github.com/timoh/craftbeer/commit/61735d29cbc782f185964c29aa4208e44611feac
https://github.com/timoh/craftbeer/commit/2fd34b454df3490fac65803b9abc51b23e24a294
https://github.com/timoh/craftbeer/commit/c59090f4d2e7bbafcc8cd13fbd15b056105f39a5

..dynamic sorting based on column name and sort order possible via API, like so:

`/home/distanced?lat=60.111&lng=24.111&page=1&sort_column=review_score&sort_order=desc`

**Comment by techstalgist** [comment]
Nice ! 

React-infinite doesn't seem to be compatible with html <table> :s, so I'll probably switch to 
http://griddlegriddle.github.io/Griddle/quickstart.html, so that I won't have to rewrite a lot of code. Griddle seems to have filtering as well, so I can enable that at the same time.

**Comment by techstalgist** [comment]
EDIT: actually Griddle is also out of the question, because the table contains some customizations that could not be implemented with Griddle.

**Comment by timoh** [comment]
Could this work:

* https://github.com/orgsync/react-list

**Comment by techstalgist** [comment]
It's possible to use custom components with Griddle. The comment was hastily written.

I'll look into Griddle next week. Yesterday I almost got React-infinite to work but I think its features are too limited for our purposes. So yes, Griddle might be worth the effort.

**Comment by timoh** [comment]
👍

**Comment by techstalgist** [comment]
Implemented in commits
https://github.com/timoh/craftbeer/commit/b92b7e06680ce93635296182a1fd1dbe75348c34
https://github.com/timoh/craftbeer/commit/438147c50a93955fac8c320f4e55cf4ff5aae732
https://github.com/timoh/craftbeer/commit/22d31c24d97097349228c66c69a6ca68cde34a07

**Comment by techstalgist** [comment]
Not being that familiar with Git, I did the following:
- said commits were made to react-infinite branch
- master was merged to react-infinite branch and 2 conflicts resolved
- react-infinite was merged to master

Maybe I could have done only one merge (react-infinite to master)?

**Comment by techstalgist** [comment]
Works now in production.
