### ISSUE TITLE
Add max availability, review title and review score to show -method in HomeController

### ISSUE THREAD

**Issue by techstalgist** [timoh/craftbeer#3]
index -method in HomeController currently returns data only from AlcoDrink:s (i.e. no review and availability data).

perhaps add a 'show' method in HomeController that returns availability and review data for AlcoDrink:s.
at least max availability, review title and review score would be useful.

**Comment by timoh** [comment]
[This commit](https://github.com/timoh/craftbeer/commit/aa6c8a1f7e40fac46c3f9a03ae6ea12ac6ae5cd7) adds a JSON API /alco_drinks/broad/:id that should provide all of this functionality.
