### ISSUE TITLE
Use popular locations in frontend

### ISSUE THREAD

**Issue by timoh** [timoh/craftbeer#34]
Commit https://github.com/timoh/craftbeer/commit/04c8d532173ab3c0337f98ac491e524943090339 makes it so that popular locations now shown on front page, and clicking on a link dispatches inputAddress(location.address), but still missing the route change to the drinks view. The logic of how that is done is not immediately apparent.

**Comment by timoh** [comment]
Commit https://github.com/timoh/craftbeer/commit/73fd9aedefbff605ec476c7c0eaa77f6233ad49e now moved problem to populating the indexpage view with the drinks as the right actions are not being called.

**Comment by techstalgist** [comment]
Fixed in https://github.com/timoh/craftbeer/commit/877993b5f0107ccbff18e5418fed398edabd4f0d

**Comment by techstalgist** [comment]
The problem probably was that geocodeAddress is asynchronous, so the execution has to wait before it's finished before the user can be redirected to indexpage.
