### ISSUE TITLE
When using search to find multiple things, check box state is lost in between

### ISSUE THREAD

**Issue by timoh** [timoh/craftbeer#37]
Steps to reproduce:
1. Use search, e.g. "IPA"
2. Check some drinks
3. Use search again with different keyword, e.g. "india pale ale"
4. Check some drinks while ensuring there remains at least one matching location
5. Click "show alko store"
6. Observe: only the latest selection is present, the one with the IPA is not

**Comment by techstalgist** [comment]
Easy to fix, because I coded that behaviour on purpose. For some reason I thought old selections would not matter.

Fixed in https://github.com/timoh/craftbeer/commit/ea81e7b2fe616c64481e07d6d753391e8dce38bb
